### ISSUE TITLE
Number of training samples

### ISSUE THREAD

**Issue by FrancescoMandru** [d-eremeev/SC-GAN#2]
How many samples did you use for training and how many epochs have you done for obtaining the results in the slides?

**Comment by d-eremeev** [comment]
@FrancescoMandru Hello!
We've used the full train dataset from Kaggle (https://www.kaggle.com/c/lyft-motion-prediction-autonomous-vehicles/data) - 22Gb. Additionally we masked non-moving ego-cars (pass agent_mask argument to AgentDataset).
Learning curve in the slides is drawn up to the end of 4th epoch with batch_size=16.
