### ISSUE TITLE
Stuck in checking stats on val

### ISSUE THREAD

**Issue by Fredtoby** [d-eremeev/SC-GAN#3]
Dear authors, how long will it last for "checking stats on val"? I have been waiting for more than 3 hours for this process. But nothing happened. Are there any tricks to make this process quicker? Thank you so much for your help.

**Comment by alexeypustynnikov** [comment]
@Fredtoby Hello! 

As pointed out in the article and README, we use only scenes with **moving** ego-cars for both training and validation.

> We select only moving (non-static) cars for prediction. This is achieved by passing a custom mask to l5kit dataset class. We consider cars which drove less than 5 meters over past second to be static.

Namely, we reported results using 20000 examples for validation. Validation process took about 10 minutes.

It might be convenient to insert tqdm into validation loop for time estimation. In our code it could be placed here:

https://github.com/d-eremeev/SC-GAN/blob/971c169899bd76beee532bcbc8620370a3906f61/utils.py#L127
